from AccountPatch import AccountPatch
from ClientAppPatch import ClientAppPatch
from ProductLoaderPatch import ProductLoaderPatch
from WindowsPatch import WindowsPatch
from EnablePhotoModePatch import EnablePhotoModePatch
